/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author satwi
 */
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
public class Delete_Books_ extends javax.swing.JFrame {

    /**
     * Creates new form Delete_Books_
     */
    public Delete_Books_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_author = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbl_price = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lbl_availability = new javax.swing.JLabel();
        txt_book_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txt_title = new javax.swing.JTextField();
        txt_subject = new javax.swing.JTextField();
        btn_view = new javax.swing.JButton();
        txt_author = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        txt_price = new javax.swing.JTextField();
        lbl_book_id = new javax.swing.JLabel();
        txt_availability = new javax.swing.JTextField();
        lbl_title = new javax.swing.JLabel();
        lbl_subject = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System (Ansh,Deepankar)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_author.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_author.setForeground(new java.awt.Color(255, 255, 255));
        lbl_author.setText("Author");
        getContentPane().add(lbl_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 156, -1, -1));

        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 332, -1, -1));

        lbl_price.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_price.setForeground(new java.awt.Color(255, 255, 255));
        lbl_price.setText("Price");
        getContentPane().add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 212, -1, -1));

        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 332, -1, -1));

        lbl_availability.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_availability.setForeground(new java.awt.Color(255, 255, 255));
        lbl_availability.setText("Availability");
        getContentPane().add(lbl_availability, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 272, -1, -1));

        txt_book_id.setEditable(false);
        txt_book_id.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        txt_book_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_book_idMouseClicked(evt);
            }
        });
        txt_book_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_book_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 35, 144, -1));

        jList1.setModel(new DefaultListModel()
        );
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 101, 110, 198));

        txt_title.setEditable(false);
        txt_title.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        getContentPane().add(txt_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 35, 139, -1));

        txt_subject.setEditable(false);
        txt_subject.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        getContentPane().add(txt_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 101, 139, -1));

        btn_view.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_view.setText("VIEW");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });
        getContentPane().add(btn_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 332, -1, -1));

        txt_author.setEditable(false);
        txt_author.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        getContentPane().add(txt_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 155, 139, -1));

        btn_delete.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 332, -1, -1));

        txt_price.setEditable(false);
        txt_price.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        getContentPane().add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 211, 139, -1));

        lbl_book_id.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_book_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_book_id.setText("Book Id");
        getContentPane().add(lbl_book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 40, -1, 16));

        txt_availability.setEditable(false);
        txt_availability.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        getContentPane().add(txt_availability, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 271, 139, -1));

        lbl_title.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Title");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 36, -1, -1));

        lbl_subject.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_subject.setForeground(new java.awt.Color(255, 255, 255));
        lbl_subject.setText("Subject");
        getContentPane().add(lbl_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 102, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1024x400 slider Cafe at FML.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, 690, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_book_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_book_idMouseClicked

    }//GEN-LAST:event_txt_book_idMouseClicked

    private void txt_book_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_book_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_book_idActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String sql = "Select * from books";
        try
        {
            Class.forName("java.sql.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            Statement stmt = con.createStatement();
            String Book_Id = (String)jList1.getSelectedValue();
            String sql1="Select * from Books where Book_Id ='"+(Book_Id)+"';";
            ResultSet rs = stmt.executeQuery(sql1);
            while(rs.next())
            {
                txt_author.setText(rs.getString("AUTHOR"));
                txt_availability.setText(rs.getString("AVAILABLE"));
                txt_book_id.setText(rs.getString("BOOK_ID"));
                txt_price.setText(rs.getString("PRICE"));
                txt_subject.setText(rs.getString("SUBJECT"));
                txt_title.setText(rs.getString("TITLE"));

            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        DefaultListModel model=(DefaultListModel)jList1.getModel();
        int rows = model.getSize();
        if(rows>0)
        {
            for(int i=0;i<rows;i++)
            {
                model.removeAllElements();
            }
        }
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            Statement stmt = con.createStatement();
            String sql="Select BOOK_ID from BOOKS;";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next())
            {
                model.addElement(rs.getString("BOOK_ID"));
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    if(txt_author.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please Enter Details");
    }
    else
    {  
        DefaultListModel model = (DefaultListModel)jList1.getModel();
        String Book_Id= (String)jList1.getSelectedValue();
        try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            Statement stmt = con.createStatement();
            int ans = JOptionPane.showConfirmDialog(this,"Do you really want to delete !");
            if(ans==JOptionPane.YES_OPTION)
            {
                String q1="Delete from Books where Book_Id = '"+(Book_Id)+"';";
                txt_author.setText("");
                txt_availability.setText("");
                txt_book_id.setText("");
                txt_price.setText("");
                txt_subject.setText("");
                txt_title.setText("");
                stmt.executeUpdate(q1);
                JOptionPane.showMessageDialog(this,"Record Deleted Successfully");
                model.removeAllElements();
                String q2="Select Book_Id from Books;";
                ResultSet rs = stmt.executeQuery(q2);

                while(rs.next())
                {
                    model.addElement(rs.getString(1));
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       new Welcome().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Books_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Books_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Books_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Books_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Books_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_view;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_availability;
    private javax.swing.JLabel lbl_book_id;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_subject;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_author;
    private javax.swing.JTextField txt_availability;
    private javax.swing.JTextField txt_book_id;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_subject;
    private javax.swing.JTextField txt_title;
    // End of variables declaration//GEN-END:variables
}
