
import java.util.TimerTask;
import javax.swing.JOptionPane;
import java.util.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author satwi
 */
public class Homepage extends javax.swing.JFrame {
int ar[]=new int[4];
public int k=0;
    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        ar[0]=1;
        ar[1]=2;
        ar[2]=3;
        ar[3]=4;
        
        Timer t=new Timer();
        TimerTask tsk=new TimerTask() {
            @Override
            public void run() {
              k++;
              switch(k){
                  case 1:
                      ad1.setVisible(true);
                      ad2.setVisible(false);
                      ad3.setVisible(false);
                      ad4.setVisible(false);
                      ad5.setVisible(false);
                      ad6.setVisible(false);
                      ad7.setVisible(false);
                      
                 break;     
                  case 2:
                      ad2.setVisible(true);
                      ad1.setVisible(false);
                      ad3.setVisible(false);
                      ad4.setVisible(false);
                      ad5.setVisible(false);
                      ad6.setVisible(false);
                      ad7.setVisible(false);
                      
                 break;
                  case 3:
                       ad3.setVisible(true); 
                       ad2.setVisible(false);
                       ad1.setVisible(false);
                       ad4.setVisible(false);
                       ad5.setVisible(false);
                       ad6.setVisible(false);
                       ad7.setVisible(false);
                  break;     
                  case 4:
                      ad4.setVisible(true);
                      ad3.setVisible(false);
                      ad2.setVisible(false);
                      ad1.setVisible(false);
                      ad5.setVisible(false);
                      ad6.setVisible(false);
                      ad7.setVisible(false);
                  break;
                  case 5:
                      ad5.setVisible(true);
                      ad4.setVisible(false);
                      ad3.setVisible(false);
                      ad2.setVisible(false);
                      ad1.setVisible(false);
                      ad6.setVisible(false);
                      ad7.setVisible(false);
                  break;
                  case 6:
                      ad6.setVisible(true);
                      ad5.setVisible(false);
                      ad4.setVisible(false);
                      ad3.setVisible(false);
                      ad2.setVisible(false);
                      ad1.setVisible(false);
                      ad7.setVisible(false);
                  break;
                  case 7:
                      ad7.setVisible(true);
                      ad6.setVisible(false);
                      ad5.setVisible(false);
                      ad4.setVisible(false);
                      ad3.setVisible(false);
                      ad2.setVisible(false);
                      ad1.setVisible(false);
                      
                  break;    
              
              
              
              }
              if(k==7)
                  k=0;
            }
        };
        t.scheduleAtFixedRate(tsk,0,2500);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ad7 = new javax.swing.JLabel();
        ad6 = new javax.swing.JLabel();
        ad5 = new javax.swing.JLabel();
        ad4 = new javax.swing.JLabel();
        ad3 = new javax.swing.JLabel();
        ad2 = new javax.swing.JLabel();
        ad1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System (Ansh,Deepankar)");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ad7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natekoehler_libraryposters_04.jpg"))); // NOI18N
        getContentPane().add(ad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        ad6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vintage-library-ads-cant-start-younger.jpg"))); // NOI18N
        getContentPane().add(ad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        ad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5.jpg"))); // NOI18N
        getContentPane().add(ad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        ad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.jpg"))); // NOI18N
        getContentPane().add(ad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        ad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        getContentPane().add(ad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        ad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.jpg"))); // NOI18N
        getContentPane().add(ad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        ad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        getContentPane().add(ad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 70)); // NOI18N
        jLabel2.setText("LIBRARY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/er-removebg-preview-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -30, 330, 360));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close-icon-rounded-squares-button-vector-4527009-removebg-preview-removebg-preview.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 810, 60, 60));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrdinaryTallAfricangroundhornbill-small.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 50, 120, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/books2.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 190, 230, 210));

        jButton5.setBackground(new java.awt.Color(51, 255, 255));
        jButton5.setFont(new java.awt.Font("Yu Gothic UI", 0, 26)); // NOI18N
        jButton5.setText("VIEW ALL BOOKS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 430, 230, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facilities.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 590, 230, 190));

        jButton6.setBackground(new java.awt.Color(51, 225, 225));
        jButton6.setFont(new java.awt.Font("Yu Gothic UI", 0, 26)); // NOI18N
        jButton6.setText("FACILITIES");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 820, 230, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e14ba967641d3963dc08bb3688ae3c80.jpeg"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 260, 200));

        jButton7.setBackground(new java.awt.Color(51, 225, 225));
        jButton7.setFont(new java.awt.Font("Yu Gothic UI", 0, 26)); // NOI18N
        jButton7.setText("VIEW PUBLISHERS");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, 260, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/findBookIcon.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 590, 240, 190));

        jButton8.setBackground(new java.awt.Color(51, 225, 225));
        jButton8.setFont(new java.awt.Font("Yu Gothic UI", 0, 26)); // NOI18N
        jButton8.setText("FIND BOOKS");
        jButton8.setToolTipText("");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 820, 240, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bookstore102.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 280, 200));

        jButton9.setBackground(new java.awt.Color(51, 225, 225));
        jButton9.setFont(new java.awt.Font("Yu Gothic UI", 0, 26)); // NOI18N
        jButton9.setText("FIND A PUBLISHER");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 290, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book-issue.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, 290, 200));

        jButton10.setBackground(new java.awt.Color(51, 225, 225));
        jButton10.setFont(new java.awt.Font("Yu Gothic UI", 0, 26)); // NOI18N
        jButton10.setText("ISSUE A BOOK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 820, 290, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about-us.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 810, 210, 60));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 38, 880, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 890, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasy.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 80, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biography.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconscience.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, -1, 80));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipe.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 40, -1, 80));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/romance.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 40, -1, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/559404-istock-512966920_0.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      int ans= JOptionPane.showConfirmDialog(this,"Please Login To View This Section !!");
       if(ans==JOptionPane.YES_OPTION)
       {
            new Login().setVisible(true);
            this.dispose();
       }
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        new Facilities_().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       new View_publishers1().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      new View_books1().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new Search_publishers11().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      //  jComboBox1.setSelectedItem(null);
       // jComboBox2.setSelectedItem(null);
    }//GEN-LAST:event_formWindowActivated

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new Search_books1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new Facilities_().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad1;
    private javax.swing.JLabel ad2;
    private javax.swing.JLabel ad3;
    private javax.swing.JLabel ad4;
    private javax.swing.JLabel ad5;
    private javax.swing.JLabel ad6;
    private javax.swing.JLabel ad7;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
