/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author satwi
 */
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Update_books extends javax.swing.JFrame {

    /**
     * Creates new form Update_books
     */
    public Update_books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_view = new javax.swing.JButton();
        lbl_book_id = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        lbl_subject = new javax.swing.JLabel();
        lbl_author = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();
        lbl_availability = new javax.swing.JLabel();
        txt_book_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txt_title = new javax.swing.JTextField();
        txt_subject = new javax.swing.JTextField();
        txt_author = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System (Ansh,Deepankar)");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_view.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_view.setText("VIEW");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });
        getContentPane().add(btn_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 428, -1, -1));

        lbl_book_id.setBackground(new java.awt.Color(0, 0, 0));
        lbl_book_id.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_book_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_book_id.setText("BOOK ID");
        getContentPane().add(lbl_book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 48, -1, 16));

        lbl_title.setBackground(new java.awt.Color(0, 0, 0));
        lbl_title.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("TITLE");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 115, -1, -1));

        lbl_subject.setBackground(new java.awt.Color(0, 0, 0));
        lbl_subject.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_subject.setForeground(new java.awt.Color(255, 255, 255));
        lbl_subject.setText("SUBJECT");
        getContentPane().add(lbl_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 184, -1, -1));

        lbl_author.setBackground(new java.awt.Color(0, 0, 0));
        lbl_author.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_author.setForeground(new java.awt.Color(255, 255, 255));
        lbl_author.setText("AUTHOR");
        getContentPane().add(lbl_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 251, -1, -1));

        lbl_price.setBackground(new java.awt.Color(0, 0, 0));
        lbl_price.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_price.setForeground(new java.awt.Color(255, 255, 255));
        lbl_price.setText("PRICE");
        getContentPane().add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 308, -1, -1));

        lbl_availability.setBackground(new java.awt.Color(0, 0, 0));
        lbl_availability.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbl_availability.setForeground(new java.awt.Color(255, 255, 255));
        lbl_availability.setText("AVAILABILITY");
        getContentPane().add(lbl_availability, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 372, -1, -1));

        txt_book_id.setEditable(false);
        txt_book_id.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        txt_book_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_book_idMouseClicked(evt);
            }
        });
        txt_book_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_book_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 42, 136, -1));

        jList1.setModel(new DefaultListModel()
        );
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 42, 110, 261));

        txt_title.setEditable(false);
        txt_title.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        getContentPane().add(txt_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 112, 136, -1));

        txt_subject.setEditable(false);
        txt_subject.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        getContentPane().add(txt_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 181, 136, -1));

        txt_author.setEditable(false);
        txt_author.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        getContentPane().add(txt_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 248, 136, -1));

        txt_price.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        txt_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_priceKeyTyped(evt);
            }
        });
        getContentPane().add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 305, 136, -1));

        btn_update.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 428, -1, -1));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 321, 110, -1));

        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 387, 110, -1));

        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 369, 136, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/branch-card.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        DefaultListModel model=(DefaultListModel)jList1.getModel();
        int rows = model.getSize();
        if(rows>0)
        {
            for(int i=0;i<rows;i++)
            {
                model.removeAllElements();
            }
        }
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            Statement stmt = con.createStatement();
            String sql="Select BOOK_ID from BOOKS;";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next())
            {
                model.addElement(rs.getString("BOOK_ID"));
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_viewActionPerformed

    private void txt_book_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_book_idMouseClicked

    }//GEN-LAST:event_txt_book_idMouseClicked

    private void txt_book_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_book_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_book_idActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String sql = "Select * from books";
        try
        {
            Class.forName("java.sql.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            Statement stmt = con.createStatement();
            String Book_Id = (String)jList1.getSelectedValue();
            String sql1="Select * from Books where Book_Id ='"+(Book_Id)+"';";
            ResultSet rs = stmt.executeQuery(sql1);
            while(rs.next())
            {
                txt_author.setText(rs.getString("AUTHOR"));
                txt_book_id.setText(rs.getString("BOOK_ID"));
                txt_price.setText(rs.getString("PRICE"));
                txt_subject.setText(rs.getString("SUBJECT"));
                txt_title.setText(rs.getString("TITLE"));
                if(rs.getString("Available").equals("YES"))
                {
                    jComboBox1.setSelectedIndex(0);
                }
                else
                {
                    jComboBox1.setSelectedIndex(1);
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(txt_author.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Details");
        }
     else
        {
              
        try
      {
          Class.forName("java.sql.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
          Statement stmt=con.createStatement();
          String Book_Id=jList1.getSelectedValue();
          int ans=JOptionPane.showConfirmDialog(this,"Do you really want to update the record");
          if(ans==JOptionPane.YES_OPTION)
          { 
              String Price=txt_price.getText();
              String Availability=(String)jComboBox1.getSelectedItem();
              String q1="update books set Price='"+(Price)+"',Available='"+(Availability)+"'  where Book_Id='"+(Book_Id)+"';";
              txt_author.setText("");
              jComboBox1.setSelectedItem(null);
              txt_book_id.setText("");
              txt_price.setText("");
              txt_subject.setText("");
              txt_title.setText("");
              stmt.executeUpdate(q1);
          JOptionPane.showMessageDialog(this, "Record Updated Successfully");
          }                           
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(this,e.getMessage());
      }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyTyped
        char kc = evt.getKeyChar();
          if (!(((kc >= '0') && (kc <= '9')) )) {
             evt.consume();
          }  
        
    }//GEN-LAST:event_txt_priceKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jComboBox1.setSelectedItem(null);
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new Welcome().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_view;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_availability;
    private javax.swing.JLabel lbl_book_id;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_subject;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_author;
    private javax.swing.JTextField txt_book_id;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_subject;
    private javax.swing.JTextField txt_title;
    // End of variables declaration//GEN-END:variables
}
